Repository shipwright-io/community, pull requests merged in 2023-08, with the labels that each got.

#159 Add issues workflow and cleanup
  .github/workflows/issues.yml
  CONTRIBUTING.md
  code-of-conduct.md
Labels: lgtm, kind/cleanup, size/L, approved

#161 Update on BETA API changes
  ships/0035-beta-api-changes.md
Labels: lgtm, approved, size/S

#163 Update README.md
  README.md
Labels: lgtm, size/XS, kind/documentation, approved
